import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import { estimatedCost, MAX_IMAGE_BYTES, normalizeProviderAnalysis, validateAnalysisRequest } from '../../supabase/functions/_shared/analysis-core';
import { MISTAKE_INTERPRETATION_ROUTE, sanitizeAiErrorCode } from '../../supabase/functions/_shared/ai-observability';
import { AnalysisFinalizationError, runAnalysisLifecycle } from '../../supabase/functions/_shared/analysis-lifecycle';

const request={requestId:'550e8400-e29b-41d4-a716-446655440000',image:{base64:'YWJj',mimeType:'image/jpeg'},locale:'pt-BR'};
describe('secure photo analysis boundary',()=>{
  it('accepts the supported locale and image contract',()=>assert.equal(validateAnalysisRequest(request).ok,true));
  it('rejects malformed and oversized images',()=>{assert.deepEqual(validateAnalysisRequest({...request,image:{base64:'not base64!',mimeType:'image/jpeg'}}),{ok:false,code:'INVALID_IMAGE'});assert.deepEqual(validateAnalysisRequest({...request,image:{base64:'A'.repeat(Math.ceil(MAX_IMAGE_BYTES/0.75)+8),mimeType:'image/jpeg'}}),{ok:false,code:'IMAGE_TOO_LARGE'});});
  it('rejects arbitrary provider enums and accepts normalized output',()=>{assert.equal(normalizeProviderAnalysis({...fixture(),errorType:'MADE_UP'},'test'),null);assert.equal(normalizeProviderAnalysis(fixture(),'test')?.errorType,'SIGN_ERROR');});
  it('keeps pricing calculation centralized and optional',()=>{assert.equal(estimatedCost(1_000_000,500_000,'0.1','0.2'),.2);assert.equal(estimatedCost(null,10,'0.1','0.2'),null);});
  it('keeps auth, idempotency and allowance enforcement server-side',()=>{const edge=readFileSync('supabase/functions/analyze-mistake/index.ts','utf8');const migration=readFileSync('supabase/migrations/20260826230759_core_persistence_ai_usage.sql','utf8');assert.match(edge,/auth:'user'/);assert.match(edge,/is_anonymous/);assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/unique \(user_id, feature, request_id\)/);assert.match(migration,/revoke all on function public\.reserve_ai_analysis/);assert.doesNotMatch(edge,/isPro|is_pro/);});
  it('keeps feature and route separate in the server-only cost ledger',()=>{const migration=readFileSync('supabase/migrations/20260906120000_ai_cost_observability.sql','utf8');const edge=readFileSync('supabase/functions/analyze-mistake/index.ts','utf8');assert.match(migration,/p_feature text,\s+p_route text,/);assert.match(migration,/revoke all on public\.ai_usage_events from anon, authenticated/);assert.match(migration,/grant execute on function public\.record_ai_usage_event[\s\S]*to service_role/);assert.match(migration,/on conflict \(user_id, feature, route, request_id, attempt\) do nothing/);assert.match(migration,/from public\.ai_analysis_requests\s+where user_id = p_user_id and feature = p_feature and status = 'completed'/);assert.match(migration,/created_at >= now\(\) - interval '1 minute'\s+\) >= v_minute/);assert.doesNotMatch(migration,/created_at >= now\(\) - interval '1 minute' and status/);assert.doesNotMatch(migration,/created_at\s*=\s*now\(\)/);assert.doesNotMatch(migration,/'ocr_local'/);assert.match(edge,/p_feature:FEATURE,p_route:MISTAKE_INTERPRETATION_ROUTE/);assert.match(edge,/complete_ai_analysis_observed/);assert.match(edge,/fail_ai_analysis_observed/);});
  it('sanitizes technical errors before they reach the observability ledger',()=>{assert.equal(sanitizeAiErrorCode('AI_PROVIDER_ERROR'),'AI_PROVIDER_ERROR');assert.equal(sanitizeAiErrorCode('provider body: private'),null);assert.equal(MISTAKE_INTERPRETATION_ROUTE,'mistake_interpretation');});
  it('records provider failure without attempting SQL completion', async()=>{let failures=0,completions=0;await assert.rejects(runAnalysisLifecycle({runProvider:async()=>{throw Object.assign(new Error('AI_PROVIDER_TIMEOUT'),{code:'AI_PROVIDER_TIMEOUT'});},complete:async()=>{completions+=1;return{data:null,error:null};},onProviderFailure:async()=>{failures+=1;},sleep:async()=>undefined}),/AI_PROVIDER_TIMEOUT/);assert.equal(failures,1);assert.equal(completions,0);});
  it('completes once after a successful provider response', async()=>{let completions=0,failures=0;const result=await runAnalysisLifecycle({runProvider:async()=>({tokens:10}),complete:async()=>{completions+=1;return{data:{state:'completed'},error:null};},onProviderFailure:async()=>{failures+=1;},sleep:async()=>undefined});assert.deepEqual(result,{state:'completed'});assert.equal(completions,1);assert.equal(failures,0);});
  it('retries the same completion payload after a transient SQL failure', async()=>{let completions=0;const seen:unknown[]=[];const providerResult={requestId:request.requestId,attempt:1,tokens:10,cost:.000001};const result=await runAnalysisLifecycle({runProvider:async()=>providerResult,complete:async(payload)=>{seen.push(payload);completions+=1;return completions===1?{data:null,error:new Error('transient')}:{data:{state:'completed'},error:null};},onProviderFailure:async()=>{assert.fail('provider failure path must not run');},sleep:async()=>undefined});assert.equal(completions,2);assert.equal(seen[0],providerResult);assert.equal(seen[1],providerResult);assert.deepEqual(result,{state:'completed'});});
  it('returns a sanitized retryable finalization error without marking provider failure', async()=>{let completions=0,failures=0;await assert.rejects(runAnalysisLifecycle({runProvider:async()=>({tokens:10}),complete:async()=>{completions+=1;return{data:null,error:new Error('private database detail')};},onProviderFailure:async()=>{failures+=1;},sleep:async()=>undefined}),error=>error instanceof AnalysisFinalizationError&&error.message==='PERSISTENCE_RETRYABLE');assert.equal(completions,3);assert.equal(failures,0);});
  it('keeps repeated SQL completion idempotent for usage, mistake and quota',()=>{const sql=readFileSync('supabase/tests/ai_cost_observability.test.sql','utf8');assert.match(sql,/repeated completion does not duplicate usage/);assert.match(sql,/repeated completion does not duplicate the corrected mistake/);assert.match(sql,/completed logical analysis increases daily quota once/);});
});
function fixture(){return{status:'identified',transcription:'x',errorSummary:'Sign changed',explanation:'Check the isolation step',correctionSteps:['Keep the sign'],suggestedSubject:'mathematics',topic:'Linear equations',suggestedCause:'calculation',errorType:'SIGN_ERROR',repairRule:'Check the sign before dividing',confidence:'high'};}
